### ISSUE TITLE
Try testing netlink communication in Github Actions

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#102]
Now that neli is using Github Actions, try interaction with ACPI and other netlink subsystems.

**Comment by joshtriplett** [comment]
To avoid making CI dependent on the capabilities and permissions of whatever Linux environment it runs in, I would suggest separately capturing dumps of netlink conversations based on examples like `getips`, and incorporating each of those dumps and corresponding neli structure constants into two separate tests: one that takes the dump and deserializes it to see if it's identical to the constant, and a *separate* test that serializes the constant and makes sure it's identical to the dump.

Ideally, most of those dumps could come from actual netlink examples, run on a Linux system where you have the requisite permissions.

However, I also think there'd be value in going back to 0.4, creating dumps by serializing a version of every neli data structure with distinct dummy values filled in, and then moving those dumps forward to 0.5 and making sure the structures deserialize to ported versions of the corresponding constants. That'll ensure that there aren't any more issues like https://github.com/jbaublitz/neli/issues/109 that came up in the 0.4 to 0.5 rewrite.
