### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#105]
Created due to #103 

@phip1611 I'm envisioning the following for the `SerError` and `DeError` structs which generated the error that was confusing for you. Because a lot of these errors are autogenerated in the `serialize` and `deserialize` macros, how does this sound? `SerError` and `DeError` will include the type of the object being serialized or deserialized, an optional struct field if it's a struct being serialized or deserialized, and what the cause of the error was. So an error in the case of your example would look something like this:

```Deserializing field error of struct Nlmsgerr could not be completed: the end of the deserialization buffer was reached before the deserialization operation could be completed; the packet received may be incomplete```

Here I'm assuming that you included no payload whatsoever after the netlink header so deserialization would have failed on the deserialization of `Nlmsgerr` [here on this line](https://github.com/jbaublitz/neli/blob/master/src/nl.rs#L214).

Would that error message be clearer?

**Comment by phip1611** [comment]
`SerError and DeError will include the type of the object being serialized or deserialized, an optional struct field if it's a struct being serialized`
This sounds perfectly right. This will help to either identify problems in a custom netlink implementation (when writing a custom kernel module) or perhaps to find some other neli-bugs. @jbaublitz

**Comment by jbaublitz** [comment]
Okay great! I'll put up a PR once I finished the design for you to look over.

**Comment by jbaublitz** [comment]
I'm still working on this as is requires more information to be passed to the macros for error messages. Because I consider macros part of the API, I will need to make some rather invasive changes to accomplish that.

**Comment by phip1611** [comment]
Don't worry, take your time. Happy holidays/merry christmas and thanks for your effort! 🎅🎄 @jbaublitz

**Comment by phip1611** [comment]
As mentioned here https://github.com/jbaublitz/neli/issues/116: It would be super useful if neli could also tell at which offset it failed or give more details / give detailed information about the bytes that could be deserialized and the ones that could not be deserialized. But I imagine this would be hard to implement with the current archtiecture, right?

 For example `nlmsg_len is 6 bytes but the struct nlmsg_error needs x bytes`

**Comment by jbaublitz** [comment]
I'm going to keep working on this but follow along with #101. So far, it's looking promising and will allow much better logging in this regard for debugging purposes.

**Comment by jbaublitz** [comment]
@phip1611 Is the improved logging sufficient for debugging?

**Comment by phip1611** [comment]
@jbaublitz hm, any idea how I can easily provoke a parsing error, so that I can verify? 

PS: I played a little bit around with the latest neli version. Looks good and error handling works fine too.

**Comment by jbaublitz** [comment]
@phip1611 One way I can think of pretty easily is to serialize an `Nlmsghdr` and then artificially increase `nl_len` in the binary representation and deserialize the buffer. You want trace logging enabled.

My main thoughts on the logging is that it may be able to be improved and if you have feedback on what you'd like to see, I'll immediately put out a patch release with logging for, for example, the part of the slice that caused the error. I didn't know how much of the slice people would want to see, etc. so I'd really like to get more concrete feedback from the people who want this.
