### ISSUE TITLE
Create an `impl Nl for u64` to help support `u64`s in Netlink responses

### ISSUE THREAD

**Issue by Dieff** [jbaublitz/neli#11]
In `src/lib.rs` there are implementations of the `Nl` trait for a number of common types. An unsigned 64 bit integer (`u64`) is another common type that does not have an yet have implementation. This type can be found in several Netlink apis, including [Wireguard](https://github.com/WireGuard/WireGuard/blob/master/src/uapi/wireguard.h) (see the attribute `WGPEER_A_RX_BYTES`). It would help developers using neli to interact with these apis if this impl was provided by the library.

The underlying libraries used by neli seem to provide the methods you would need to create `impl Nl for u64` more or less the same way as the the `impl Nl for u32` and `impl Nl for u16` that already exist in neli. It should be a simple matter to add the support for `u64` as well.

I think I will need this to go forward with a project I am working on now: interfacing with the Wireguard kernel api (generic netlink) using neli. I could submit a pull request with my impl added to this library.

I would love some feedback about adding support (`Nl` `impl`s) for this type and other Wireguard related types to Neli.

**Comment by jbaublitz** [comment]
@Dieff Hey there! I'm happy to accept a PR or work this into the 0.4.0 release. Either way, just let me know which you would prefer so we don't duplicate work.

**Comment by jbaublitz** [comment]
If you would like it as soon as possible, let me know and I'll branch off of the last release and add a revision release and push that to crates.io then incorporate that into 0.4.0. Unfortunately I've been pulled in a few different directions so that release is taking a bit longer than I'd hoped.

**Comment by Dieff** [comment]
I think I'll take a stab at writing the impl as it seems pretty simple and it would be nice for me to have quickly. I'll open a pr when I get it working.

**Comment by jbaublitz** [comment]
#12 merged.

As discussed, please open another issue regarding the `impl Nl` discussion as I'd definitely like to resolve that with you. Thanks!
