### ISSUE TITLE
Socket buffer should clear itself after deserialize failure happened, because afterwards all operations fail

### ISSUE THREAD

**Issue by phip1611** [jbaublitz/neli#116]
I use neli custom generic netlink families. I'm pretty sure that this time the bug is inside neli and not my kernel module. I'm sending an error message from the kernel. `nl_type` is `NLMSG_ERR (0x2)` and the payload is only `struct nlmsgerr`.

(If I send regular messages everthing works. I can send thousands of messages in a loop without bugs. It's about the struct nlmsgerr in this case.)

I'm pretty sure that I'm doing it correctly, since I used original Linux code as reference.

The first error message is recognized perfectly fine. But after this point all "ok" and error messages are also rejected with the same problem.  It says `Deserializing type Nlmsghdr could not be completed: the deserialization operation completed before all of the data in the buffer could be consumed; the packet being deserialized may be of the wrong type or an incorrectly sized deserialization buffer may have been provided to the deserialization operation`.

**What I did in userland**
I send a generic netlink message to the kernel which forces an error response.

**Two suggestions for improvements:**

- it would be really useful if https://github.com/jbaublitz/neli/issues/105 would also tell at which offset it failed. For example `nlmsg_len does not match the buffer: 4 bytes are missing` / is too long/too small or so. Currentl I can't figure out where neli fails. It tells me it can't deserialize struct Nlmsghdr.. but why? What bytes are missing?
- After a deserialize failure the socket buffer should be resetted / zeroed, so that future operations will not also fail (or some corresponding internal state; depending on neli implementation)

The code I'm using to send nlmsg_error struct:
```C
void ocp_reply_with_error(struct genl_info *info, int err_code) {
    struct sk_buff *reply_skb;
    int rc;
    struct nlmsghdr *nlmsghdr;
    struct nlmsgerr *nlmsgerr;
    size_t payload_size;

    // netlink standard expects a negative error code.
    // at this point it can happen that we may receive
    // the positive value. Therefore we negate it.

    if (err_code > 0) {
        err_code = -err_code;
    }

    // that's all the payload that we send
    payload_size = sizeof(struct nlmsgerr);

    // just allocates memory
    reply_skb = nlmsg_new(NLMSG_GOODSIZE, GFP_KERNEL);;
    if (reply_skb == NULL) {
        opr_err("ocp_nlmsg_new() failed\n");
        return;
    }

    // We don't send a generic netlink message (generic netlink header after netlink header)
    // we only send a netlink message here!

    // Code similar to https://elixir.bootlin.com/linux/v5.4.86/source/net/netlink/af_netlink.c#L2382

    // puts attributes into netlink header and returns the pointer to the
    // beginning of the netlink header (inside the socket buffer)
    nlmsghdr = nlmsg_put(reply_skb, info->snd_portid, 0, NLMSG_ERROR, payload_size, 0);
    if (nlmsghdr == NULL) {
        opr_err("genlmsg_put() failed because of ENOMEM\n");
        return;
    }

    // returns pointer to head of message payload
    nlmsgerr = nlmsg_data(nlmsghdr);
    // negative status code
    nlmsgerr->error = err_code;
    // netlink header that caused the problem
    // memcpy(&nlmsgerr->msg, info->nlhdr, info->nlhdr->nlmsg_len);
    // for now I only append the pure netlink header of the request and no further data
    // (like gen netlink header or attributes)
    memcpy(&nlmsgerr->msg, info->nlhdr, payload_size);

    // make sure that no userland lib wants to read more data than is available as of now
    // so far we only send the header and not the original attributes
    nlmsgerr->msg.nlmsg_len = sizeof(struct nlmsghdr);

    // update size in netlink header
    nlmsg_end(reply_skb, nlmsghdr);

    // Send the message back to the sender
    rc = nlmsg_unicast(genl_info_net(info)->genl_sock, reply_skb, info->snd_portid);

    if (rc != 0) {
        opr_err("genlmsg_reply() failed because of %d\n", rc);
        return;
    }
}
```

**Comment by phip1611** [comment]
*UPDATE* This seems to work in neli 0.5.2 but not in 0.5.1. Since upgrading to 0.5.2 it works I guess :)

**Comment by jbaublitz** [comment]
To debug this effectively, could you provide me with a pretty printed representation of the entire buffer that gets read from the socket with no processing?

**Comment by jbaublitz** [comment]
> it would be really useful if #105 would also tell at which offset it failed. For example nlmsg_len does not match the buffer: 4 bytes are missing / is too long/too small or so. Currentl I can't figure out where neli fails. It tells me it can't deserialize struct Nlmsghdr.. but why? What bytes are missing?

I can definitely work on further improving that error message. Please provide that suggestion in the linked PR so I can keep track of it.

> After a deserialize failure the socket buffer should be resetted / zeroed, so that future operations will not also fail (or some corresponding internal state; depending on neli implementation)

This is not exactly possible. Due to the nature of netlink being a datagram protocol, resetting the buffer could cause the user to lose data that was sent in a packet after the packet currently being processed. I would be happy, though, to offer a method to fast forward to the next packet and try that. Would that be acceptable for you?

**Comment by jbaublitz** [comment]
@phip1611 Is this resolved?

**Comment by phip1611** [comment]
I have this on my todo list. I have an uni exam next week but after that I'll have time to look at this again.

**Comment by phip1611** [comment]
Hi! I have an update on this @jbaublitz. Originally I created this because I had problems with `NLMSG_ERR` replies. I can now verify that `neli` has indeed a bug with parsing `NLMSG_ERR` replies, at least in my case. I'm sure this is a bug of neli, because other libraries (like `libnl` for `C` work). Also the packet buffer looks fine.

**What I did**
Very basic custom Netlink family (in custom Kernel module) that has a command "reply with error" (0x2) with a corresponding callback.
Implementation of the callback: https://github.com/phip1611/generic-netlink-user-kernel-rust/blob/534aa4c5eb0cd81a412f5445b3bbccc092ba61b7/kernel-mod/gnl_foobar_xmpl.c#L403 

According to the Netlink spec ([kernel code](https://elixir.bootlin.com/linux/v5.11/source/net/netlink/af_netlink.c#L2499),  [lnw.net](https://lwn.net/Articles/208755/)) Netlink will reply with an error message if the callback in the kernel returns a negative number. You can also verify this in the Linux kernel code link I provide.

**Expected behaviour**
`neli` should follow the Netlink error guidlines, see [manpage](https://man7.org/linux/man-pages/man7/netlink.7.html) and tell it received a `NLMSG_ERR` packet.

**Actual behaviour (BUG)**
`neli` tells "Unparsed data left in buffer" when I call `recv()` / throws error.

**Buffer**
![neli bug](https://user-images.githubusercontent.com/5737016/108594214-df9fe580-7378-11eb-94fb-fcc855844236.png)


I'm looking forward to work on a fix with you. I can provide more information if you want. 

PS: Depending on your comments on this: Maybe we should change the title of this issue to fit the new property of this bug better.

**Comment by jbaublitz** [comment]
@phip1611 If I'm understanding the picture that you posted of the strace run, this is actually a bug in your kernel module. As you can see [here under the `nlmsgerr` documentation](https://www.man7.org/linux/man-pages/man7/netlink.7.html), error messages should never send back the payload of the offending message, only the header:

```
struct nlmsgerr {
    int error;        /* Negative errno or 0 for acknowledgements */
    struct nlmsghdr msg;  /* Message header that caused the error */
};
```

It appears from your diagram that you are passing back the whole packet. While libnl may support this, this is a bug in your code. neli does more checks than libnl so there may be some invalid packets that do not cause an error with libnl that will cause an error with neli.

**Comment by jbaublitz** [comment]
I am happy to work on the original request, but this appears to be working as intended.

**Comment by phip1611** [comment]
You're right in the regard that `neli` follows the Netlink manpage @jbaublitz . But I just found **Netlink manpage and the Linux kernel code do not match.**  The manpage is wrong when it tells that there is only the Netlink header. It is the complete original packet, including all its payload.

> "... of the strace run, this is actually a bug in your kernel module..."

Technically it is not my kernel module that sends the ACK message but the Netlink system (`net/netlink/af_netlink.c`) itself.

In this link [0] one can see that the payload of the message is not only the netlink header but the complete message (length of original Netlink message that resulted in the error), if  `err` is true (not `0`) and `NETLINK_F_CAP_ACK` is not set:
```
if (err && !(nlk->flags & NETLINK_F_CAP_ACK))
		payload += nlmsg_len(nlh);
```

In line 2440 [1] you can see that the whole packet is put into the socket buffer and not just the Netlink header.
```
memcpy(&errmsg->msg, nlh, payload > sizeof(*errmsg) ? nlh->nlmsg_len : sizeof(*nlh))
```

[0] https://elixir.bootlin.com/linux/v5.11/source/net/netlink/af_netlink.c#L2416
[1] https://elixir.bootlin.com/linux/v5.11/source/net/netlink/af_netlink.c#L2440

**Comment by jbaublitz** [comment]
There does appear to be a documentation discrepancy. I will have to think about this a bit because it appears that there are times where the payload is passed back and others where it is not even when it is an error. I think that's going to be the data structure challenge for this.

**Comment by phip1611** [comment]
PS: One more proof for this: https://elixir.bootlin.com/linux/v5.11/source/include/uapi/linux/netlink.h#L113 

I try to find out where I can submit a patch for the Netlink manpage.

**Comment by jbaublitz** [comment]
@phip1611 I've added a bug report template for future bug reports and has a section specifically devoted to netlink documentation mistakes. This seems to happen rather often.
