### ISSUE TITLE
Getting an AttrHandle for rtnl attributes?

### ISSUE THREAD

**Issue by joshtriplett** [jbaublitz/neli#122]
Given a `Genlmsghdr`, you can call `get_attr_handle` to get an `AttrHandle`, from which you can call things like `get_attr_payload_as`.

However, I don't see any means of doing the same with an rtnl message. You can get an `AttrHandle` for nested attributes, but not for the top-level attributes in the message.

**Comment by jbaublitz** [comment]
You're right that there are no convenience methods for this. You can construct an `AttrHandle` like so:

```
fn attr_handle(rtmsg: &Rtmsg) -> AttrHandle<'_, Rta, Buffer> {
    AttrHandle::Borrowed(rtmsg.rtattrs.as_ref())
}
```
for example. I understand that this might not be ideal and I'm happy to discuss a better way of doing this.

Given that `RtBuffer` is contained in a wide variety of structs, I'm hesitating to just implement a helper method for each one. I'd prefer potentially moving the `.get_attr_handle()` to the `RtBuffer` and `GenlBuffer` structs and then calling these new type-defined methods from `Genlmsghdr::get_attr_handle()` for backwards compatibility. How does that sound to you?

**Comment by joshtriplett** [comment]
@jbaublitz Having a `get_attr_handle` method on `RtBuffer` and `GenlBuffer` sounds perfectly reasonable to me. Thank you.

**Comment by jbaublitz** [comment]
Okay excellent! I'll probably put this out in the next patch release.
