### ISSUE TITLE
Remove nested argument for NlAttr::new

### ISSUE THREAD

**Issue by joshtriplett** [jbaublitz/neli#124]
NlAttr::new accepts an argument to set the "has nested attributes" flag for the attribute. However, this flag should generally match the presence of nested attributes. NlAttr::new could drop that argument, and instead automatically set the flag to `true` when adding a nested attribute.

For the benefit of kernel protocols that handle the nested flag incorrectly, there could be a `set_nested` method that directly sets the flag to true or false, ignoring whether there are actually nested attributes. This method's documentation should explicitly state that it doesn't normally need to be called, that the nested flag is set automatically, and that it should only be called to work around kernel bugs. (It would be nice if that documentation could make reference to at least one *specific* kernel netlink protocol that's broken in that way.)

**Comment by jbaublitz** [comment]
Pushing this back 0.7.0.
