### ISSUE TITLE
Use a builder method for the network-endian flag of NlAttr::new

### ISSUE THREAD

**Issue by joshtriplett** [jbaublitz/neli#125]
NlAttr::new accepts a boolean flag indicating whether the packet is host-endian (`false`) or network-endian (`true`).

In the next major revision, please consider changing that to a builder method (`.set_network_endian`), to make invocations more self-documenting, and briefer for the common case of not changing the default.

**Comment by jbaublitz** [comment]
Closing in favor of #83 as this is related to that discussion.
