### ISSUE TITLE
Users cannot cleanly define new `impl Nl`s for common types because of orphan trait rules

### ISSUE THREAD

**Issue by Dieff** [jbaublitz/neli#13]
It is common when using `neli` to find Netlink message attributes that map to some sort of C data structure, like `struct timespec` or `struct in_addr`. When working with Netlink apis that send back this type of message, it makes sense to create an implementation of `Nl` for whatever data type the attribute uses, and then incorporate it into code that decodes or encodes the messages. Unfortunately, it is impossible for users to create their own implementations of `Nl` for types from `libc` or `std` because this would violate Rust's [orphan rules](https://github.com/Ixrec/rust-orphan-rules).

The best that I can do is create a wrapper for the actual type that you want to decode. So, for example, when netlink sends a response with a type of `struct timespec` and I want to turn that into `std::time::Duration` for use in my code I have to create a wrapper struct for either `libc::timespec` or possibly `std::time::Duration` and then read the fields from the wrapper in order to create a actual type I wanted to use. I think that this makes using `neli` a little less friendly 

Maybe one solution would be for `neli` to have implementations of `Nl` for a bunch of the common types users might run into when working with Netlink so that the problem becomes rare.

On a related note, I have created `impl Nl`s to serialize a few common C structs from Netlink responses. If you are interested in adding `impl Nl for libc::timespec`, `impl Nl for libc::in_addr`, or `impl Nl for libc::in6_addr` I can move my `impl`s to `neli` and open pull requests for them.

**Comment by jbaublitz** [comment]
Hi @Dieff, my preference would be to allow either but ultimately be very PR-friendly for more common types much like the `libc` crate is for constants. Originally I envisioned users writing their own types but I want to support as many common workflows out of the box as possible. If you could post a more exhaustive list here of types you'd like to see included, I'd be happy to discuss whether that sounds like a reasonable addition to `neli`. My initial reaction is that this makes a lot of sense for common types like `libc::timespec` for example and I would love to continue with the direction I started going in with integer types, strings, and vectors by officially supporting these.

**Comment by jbaublitz** [comment]
I'm going to close out this issue as I never heard back. My current suggestion until I hear otherwise is either wrap the type in a newtype struct in your code or contribute a PR for more generally useful types if you don't want to have to support it. I don't see a whole lot of other options unfortunately after reading up on this. Thanks for bringing this up!
