### ISSUE TITLE
Serialization error

### ISSUE THREAD

**Issue by fpagliughi** [jbaublitz/neli#136]
Hi. I'm trying to send a link up (or down) request to a CAN bus interface like this:

```
    let sock = NlSocketHandle::connect(NlFamily::Route, Some(my_pid), U32Bitmask::empty())?;

    let info = Ifinfomsg::up(
        RtAddrFamily::Unspecified,
        Arphrd::Netrom,
        my_if_index as c_int,
        RtBuffer::new()
    );

    let hdr = Nlmsghdr::new(
        None,
        Rtm::Newlink,
        NlmFFlags::new(&[NlmF::Request, NlmF::Ack]),
        None,
        None,
        NlPayload::Payload(info),
    );

    sock.send(hdr)?;
```

but keep getting a serialization error:
```
The buffer was too small for the requested serialization operation
```

Am I doing something obviously stupid?
Thanks

**Comment by jbaublitz** [comment]
I'm unable to reproduce this on the master branch. Are you using 0.5.2? If so, it could be related to #118. I plan to release 0.5.3 sometime today.

**Comment by fpagliughi** [comment]
Yes this was with v0.5.2. I will try `master` right now...

**Comment by fpagliughi** [comment]
Yup, that seemed to do the trick! It's working now.

Thanks for the quick reply.

**Comment by jbaublitz** [comment]
Not a problem! The release is just blocking on #138.
