### ISSUE TITLE
mcast_membership methods do not work appropriately

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#141]
@Kloenk I'm working on #138 and bumped into another bug. I'm uncertain whether this is a newer kernel change but:

```rust
    /// Join multicast groups for a socket.
    pub fn add_mcast_membership(&self, groups: U32Bitmask) -> Result<(), io::Error> {
        match unsafe {
            libc::setsockopt(
                self.fd,
                libc::SOL_NETLINK,
                 &u32 NETLINK_ADD_MEMBERSHIP,
                &*groups as *const _ as *const libc::c_void,
                size_of::<u32>() as libc::socklen_t,
            )   
        } {
            i if i == 0 => Ok(()),
            _ => Err(io::Error::last_os_error()),
        }   
    }
```

is not working with kernel `5.4.0-65-generic`. After looking into the documentation and the kernel code, I'm not seeing a change from `groups` being a bitmask to a single value or an array and this may be leftover from when I used to set the `nl_groups` field in the netlink socket address, but I was almost positive that this used to work as is on my system. Is this working on your system as a bitmask and if so, what kernel version are you running?

**Comment by Kloenk** [comment]
Not worked with mcast yet, not event looked up what the do :-).
Im only working with the normal nl80211 family, on the kernel packaged as kernel in nixpkgs. Not sure of the exact version at the moment.

**Comment by jbaublitz** [comment]
Okay, I'll assume this is a bug.
