### ISSUE TITLE
Add getSockName to get the pid of the netlink link

### ISSUE THREAD

**Issue by hube12** [jbaublitz/neli#142]
**Would adding this feature cause a breaking change?**
no

Hello,
I would like to see if it would be possible to add such function to socket.rs (and expose it in the handle)
```rust
/// Get the current pid address and group from sock name
    pub fn get_pid_from_sock_name(&self)-> Result<(u32,u32), io::Error>{
        let mut addr = mem::MaybeUninit::uninit();
        let mut len = mem::size_of::<libc::sockaddr_storage>() as libc::socklen_t;
        match unsafe {libc::getsockname(
            self.fd,
            addr.as_mut_ptr() as *mut libc::sockaddr,
            &mut len,
        )}{
            i if i == 0 => Ok(()),
            _ => Err(io::Error::last_os_error()),
        };
        let filled_addr:&libc::sockaddr_storage=unsafe{&addr.assume_init()};
        let filled_len:usize=len as usize;
        assert!(filled_len <= mem::size_of::<libc::sockaddr_un>());
        if filled_len < mem::size_of_val(&filled_addr.ss_family) {
            return Err(io::Error::last_os_error());
        }
        match libc::c_int::from(filled_addr.ss_family){
            libc::AF_NETLINK=> {
                let snl:*const  libc::sockaddr_nl= unsafe { filled_addr as *const _ as *const libc::sockaddr_nl };
                let pid:u32=unsafe{(*snl).nl_pid};
                let groups:u32=unsafe{(*snl).nl_groups};
                Ok((pid,groups))
            },
            _=>Err(io::Error::from(io::ErrorKind::InvalidData)),
        }
    }
```
(help for source : https://docs.rs/nix/0.20.0/src/nix/sys/socket/mod.rs.html#1647 )

This would allow to get the registered pid of the netlink socket after binding, I think it would be a nice addition, however as it use a few unsafe, I would totally get why you wouldn't want to add it but having a way to get the socket name would be great.

Regards,
Neil

**Comment by jbaublitz** [comment]
Hi Neil! I think this is a great idea. My initial response is that this belongs in `NlSocketHandle` with a lower level method in `NlSocket`. How does that sound to you? Given that the PID of a socket is autoassigned if 0 is passed in, I think this would be very helpful to provide.

**Comment by hube12** [comment]
@jbaublitz That sounds great, I can make a quick PR with that code as a lower level method and a higher level exposed method to use it (since I already use it in my fork). Or if you want to do it, well I gave you most of the pointers ;).
