### ISSUE TITLE
Returning Ack/Empty from recv/iter is a breaking change in 0.5.3

### ISSUE THREAD

**Issue by joshtriplett** [jbaublitz/neli#149]
**Version of neli**
0.5.3

**Describe the bug**
The change to make recv/iter return NlPayload::Ack or NlPayload::Empty messages breaks existing code that relied on it not returning such messages.

**To Reproduce**
Build and run 0.5.2's `getips` example on 0.5.3, and observe the error.

0.5.3 has been released at this point, and I can update the code I was using to accommodate the change. I'm not sure it's worth yanking that version at this point. But in general, this kind of breaking change would be worth reflecting in semver; this should have been 0.6. Please don't hesitate to increase the major version; that helps people know they may need to update their code when upgrading to the new version.

**Comment by joshtriplett** [comment]
Corrected the title and message: the actual failure seems to stem from processing messages with `NlPayload::Empty`.

**Comment by jbaublitz** [comment]
I understand the concern, and I don't intend to do this again, but this was under the larger umbrella of a bug fix. I will try to put up some sort of guidelines around breaking changes vs. bug fixes and request your feedback on it as I think this sort of question is not always necessarily straightforward. For example, if a user depends on broken behavior and a patch version fixes that behavior, I do not personally think that fixing that requires a minor version bump. However this does technically count as a breaking change as the original code will stop working. The change I made for the bug fix was probably too far reaching to be considered a reasonable bug fix so I'll put some thought into what a reasonable set of guidelines would be (for example, don't change behavior in a patch version that is not technically broken even when required for the resolution of the broken behavior).

**Comment by joshtriplett** [comment]
> For example, if a user depends on broken behavior and a patch version fixes that behavior, I do not personally think that fixing that requires a minor version bump.

Most crates I've seen do tend to treat that as a breaking change, if anyone actually depends on the previous behavior, and if the previous behavior was actually usable.

The principle I've sometimes used is, if something had a bug that made it not possible to use correctly, such that any possible code using it would fail at either compile time or runtime, then it's absolutely OK to break its ABI in the course of fixing the bug, because it can only affect non-working code.

But in this case, it was possible to build correct code that used the interface, and in fact many usages of the interface would likely work, assuming they didn't *depend* on returns of `Empty`.

To be clear, I'm *not* suggesting that it was worth spending any effort trying to work around this (e.g. introducing a variant of recv, or a flag). I think the change you made was the right one; I'm just suggesting bumping semver accordingly, so that people know they need to update their code.

My experience with this change was doing `cargo upgrade`, rebuilding, deploying a new version, and then getting an error at runtime. It took me a little time to start suspecting the neli upgrade, and it took longer to figure out the nature of the change. I did see the changelog entry saying that the behavior of `recv` had changed, but that same entry also said to use `iter` for handling of streams of messages, so I'd been assuming that `iter` would behave the same.

**Comment by jbaublitz** [comment]
Okay I'll keep this in mind! For now I'm going to close this and err on the conservative side moving forward. I don't think I really need documentation on this and can just ensure that there are no breaking changes in patch versions moving forward even if I've documented them and they're a part of a bug fix. That sounds totally reasonable putting myself in a user's shoes.
