### ISSUE TITLE
Inconsitence behavior between C and Rust API

### ISSUE THREAD

**Issue by Gottox** [jbaublitz/neli#155]
**Version of neli**
0.6.0

**Does the documentation specify that neli's behavior is correct?**
yes:

```
       NETLINK_ADD_MEMBERSHIP, NETLINK_DROP_MEMBERSHIP (since Linux 2.6.14)
              Join/leave a group specified by optval.
```

**Does there appear to be a mistake in the netlink documentation based on the kernel code?**
No further information available yet.

**Describe the bug**
In contrast to the C API of netlink, *neli* does not pass nl_group to the kernel through the `bind()` call. Instead *neli* sets the group to `0` and calls `add_mcast_membership()` afterwards. It looks like these two methods are not equivalent:

I took [this example code](https://stackoverflow.com/questions/579783/how-to-detect-ip-address-change-programmatically-in-linux), [roughly translated it to Rust](https://gist.github.com/Gottox/0fdd1fbb443dc0422464910b5313fd12#file-main-rs) and observed the behavior with strace. The C code correctly reports changes of IP-addresses, whereas the Rust code fails to report anything.

**To Reproduce**
1. `cargo new netlink_test`
2. `wget -Onetlink_test/src/main.rs https://gist.githubusercontent.com/Gottox/0fdd1fbb443dc0422464910b5313fd12/raw/f05ecfe54209d4c281becc108c38059f022c5e7c/main.rs`
3. `cd netlink_test`
3. `cargo build` (make sure to have sufficient privileges)
4. `sudo strace /path/to/executable`
4. `ifconfig <interface> 192.168.1.1`
5. `ifconfig <interface> 192.168.1.2`

**Expected behavior**
the test program should receive events from the kernel

**Actual behavior**
The test program produces no output

**Additional context**
The [C variant](https://gist.github.com/Gottox/0fdd1fbb443dc0422464910b5313fd12#file-netlink_test-c) compiled with `gcc netlink_test.c; sudo strace ./a.out` works as expected. The difference can be seen in the strace:

* Rust Variant:
```
sudo strace /work/tox/cargo-target/debug/netlink_test
[ ... ]
socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE) = 3
bind(3, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
setsockopt(3, SOL_NETLINK, NETLINK_ADD_MEMBERSHIP, [16], 4) = 0
[ ... ]
```

* C Variant:
```
sudo strace ./a.out
[ ... ]
socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE) = 3
bind(3, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000010}, 12) = 0
[ ... ]
```

This patch fixes the behavior in Neli:
```diff
diff --git a/src/socket.rs b/src/socket.rs
index 7bd86e1..cf7008d 100644
--- a/src/socket.rs
+++ b/src/socket.rs
@@ -125,7 +125,7 @@ impl NlSocket {
         let mut nladdr = unsafe { zeroed::<libc::sockaddr_nl>() };
         nladdr.nl_family = libc::c_int::from(AddrFamily::Netlink) as u16;
         nladdr.nl_pid = pid.unwrap_or(0);
-        nladdr.nl_groups = 0;
+        nladdr.nl_groups = groups.iter().fold(0, |acc, x| acc | x);
         match unsafe {
             libc::bind(
                 self.fd,
@@ -136,9 +136,6 @@ impl NlSocket {
             i if i >= 0 => (),
             _ => return Err(io::Error::last_os_error()),
         };
-        if !groups.is_empty() {
-            self.add_mcast_membership(groups)?;
-        }
         Ok(())
     }
 
```

kernel:
```
$ uname -a
Linux rootkit 5.14.16_1 #1 SMP Thu Nov 4 17:30:43 UTC 2021 x86_64 GNU/Linux
```

**Comment by jbaublitz** [comment]
Hi @Gottox, I need to do more research on this one, but if I'm remembering correctly from the last time I looked deeply into this code, the reason for this is a difference in the format of the bind call.

For some context, my original code used the `nl_groups` parameter, but at a certain point, this stopped working. I read up on it a bit and found out that `nl_groups` appeared to be considered deprecated. From the man pages, it appears that it still works but requires elevated privileges.

The current code appears to work on my end, and my guess for why is that it appears you are using a bitmask format while I am using an integer identifier format on my end. For example, netlink will often take an approach where converting a value from the bind format to the sockopt format is defined as follows: `bind_value = 1 << (sockopt_value - 1)`. At a high level, what this means is that the sockopt value is equivalent to the nth bit being set for the bitmask. So a bind value of 0x1 converts to 1 for the sockopt_value. The bind_value of 0x8 converts to 4 for the sockopt_value.

Does taking that approach solve the problem? Please see this example as well for a working example of how to subscribe to multicast groups. https://github.com/jbaublitz/neli/blob/main/examples/genl_stream.rs

**Comment by jbaublitz** [comment]
@Gottox Did this resolve your issue?

**Comment by jbaublitz** [comment]
Closing. Feel free to let me know if it's still a problem!
