### ISSUE TITLE
neli::tokio::NlSocket can't decode NLMSG_DONE.

### ISSUE THREAD

**Issue by isomer** [jbaublitz/neli#165]
**Version of neli**
v0.6.0

**Does the documentation specify that neil's behavior is correct?**
It's unclear.

> Netlink is a datagram-oriented service.  Both SOCK_RAW and SOCK_DGRAM are valid values for socket_type.  However, the netlink protocol does not distinguish between datagram and raw sockets.

But:
> Netlink messages consist of a byte stream with one or multiple nlmsghdr headers and associated payload.

**Does there appear to be a mistake in the netlink documentation based on the kernel code?**

I'm having trouble tracing exactly what's going on, so I'm not entirely sure who is at fault here, however parts of neli work and other parts don't, so I suspect the problem is somewhere in neli.

**Describe the bug**
`neli::socket::tokio::NlSocket` appears to fail with:
```
Wrapped(
    IOError(
        Error {
            kind: UnexpectedEof,
            message: "failed to fill whole buffer",
        },
    ),
)
```
when reading `NLMSG_DONE` messages.  Compared to `neli::socket::NlSocket` which seems fine.

I've not managed to figure out what is saying "failed to fill the whole buffer", I suspect the error message is coming from `std::io::Cursor` somewhere inside the macro expansion of `from_bytes_with_input`, but I'm unsure.

**To Reproduce**
Program fails, using neli::socket::tokio::NlSocket:
```rust
use neli::socket::tokio::NlSocket;
use neli::{
    consts::{
        nl::{GenlId, NlmF, NlmFFlags},
        socket::NlFamily,
    },
    err::DeError,
    genl::Genlmsghdr,
    nl::{NlPayload, Nlmsghdr},
    socket::NlSocketHandle,
    types::{GenlBuffer, NlBuffer},
};

#[neli::neli_enum(serialized_type = "u8")]
pub enum Nl80211Command {
    Unspecified = 0,
    GetWiPhy = 1,
    /* Many many more elided */
}
impl neli::consts::genl::Cmd for Nl80211Command {}

#[neli::neli_enum(serialized_type = "u16")]
pub enum Nl80211Attribute {
    Unspecified = 0,

    Wiphy = 1,
    /* Literally hundreds elided */
}
impl neli::consts::genl::NlAttrType for Nl80211Attribute {}

fn handle(msg: Nlmsghdr<GenlId, Genlmsghdr<Nl80211Command, Nl80211Attribute>>) {
    println!("msg={:?}", msg.nl_type);
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut sock = NlSocketHandle::connect(
        NlFamily::Generic, /* family */
        Some(0),           /* pid */
        &[],               /* groups */
    )?;
    let family_id = sock.resolve_genl_family("nl80211")?;

    let mut ss = NlSocket::new(sock)?;

    let req = &Nlmsghdr::new(
        /* len */ None,
        /* type */ family_id,
        /* flags */ NlmFFlags::new(&[NlmF::Request, NlmF::Dump, NlmF::Ack]),
        /* seq */ Some(1),
        /* pid */ Some(0),
        /* payload */
        NlPayload::Payload(Genlmsghdr::<Nl80211Command, Nl80211Attribute>::new(
            /* cmd */ Nl80211Command::GetWiPhy,
            /* version */ 1,
            /* attrs */ GenlBuffer::new(),
        )),
    );

    ss.send(req).await?;

    let mut buffer = Vec::new();

    loop {
        let data = ss.recv(&mut buffer).await;
        match data {
            Ok(msgs) => {
                println!("msgs: {:?}", msgs);
                for msg in msgs {
                    handle(msg);
                }
            }
            Err(e) => {
                println!("err: {:#?}", e);
            }
        }
    }
}
```

Compare/contrast the same program using `neli::socket::NlSocketHandle`:
```rust
use neli::socket::NlSocket;
use neli::{
    consts::{
        nl::{GenlId, NlmF, NlmFFlags},
        socket::NlFamily,
    },
    err::DeError,
    genl::Genlmsghdr,
    nl::{NlPayload, Nlmsghdr},
    socket::NlSocketHandle,
    types::{GenlBuffer, NlBuffer},
};

#[neli::neli_enum(serialized_type = "u8")]
pub enum Nl80211Command {
    Unspecified = 0,
    GetWiPhy = 1,
    /* Many many more elided */
}
impl neli::consts::genl::Cmd for Nl80211Command {}

#[neli::neli_enum(serialized_type = "u16")]
pub enum Nl80211Attribute {
    Unspecified = 0,

    Wiphy = 1,
    /* Literally hundreds elided */
}
impl neli::consts::genl::NlAttrType for Nl80211Attribute {}

fn handle(msg: Nlmsghdr<GenlId, Genlmsghdr<Nl80211Command, Nl80211Attribute>>) {
    println!("msg={:?}", msg.nl_type);
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut sock = NlSocketHandle::connect(
        NlFamily::Generic, /* family */
        Some(0),           /* pid */
        &[],               /* groups */
    )?;
    let family_id = sock.resolve_genl_family("nl80211")?;

    let req = Nlmsghdr::new(
        /* len */ None,
        /* type */ family_id,
        /* flags */ NlmFFlags::new(&[NlmF::Request, NlmF::Dump, NlmF::Ack]),
        /* seq */ Some(1),
        /* pid */ Some(0),
        /* payload */
        NlPayload::Payload(Genlmsghdr::<Nl80211Command, Nl80211Attribute>::new(
            /* cmd */ Nl80211Command::GetWiPhy,
            /* version */ 1,
            /* attrs */ GenlBuffer::new(),
        )),
   );

    sock.send(req)?;

    loop {
        let data = sock.recv();
        match data {
            Ok(msgs) => {
                println!("msgs: {:?}", msgs);
                for msg in msgs {
                    handle(msg);
                }
            }
            Err(e) => {
                println!("err: {:#?}", e);
            }
        }
    }
}
```

This demonstrates the problem both on machines without wifi interfaces, and machines with wifi interfaces (since the NLMSG_DONE message appears in both).  It should not require root or special privileges to run.

**Expected behavior**
Both programs should end with NLMSG_DONE (which these programs show as UnrecognizedConst(3)).  Instead only the non-async version does so, and the async version ends with the error "failed to fill the whole buffer".

**Comment by jbaublitz** [comment]
@isomer Thanks for reporting this!

A few notes:

Firstly, please look at #147 and provide feedback if you have any input. I want to expand tokio functionality further but I'd like some feedback from people who are actually using it. If you have thoughts on the existing implementation or desired features, please leave them there!

I'm currently adding your code to the example directory so that I can include it in CI to ensure that it doesn't break in the future.

I think I've found the problem. It appears that for an empty payload, netlink returns 4 zeros to pad it to the alignment length and those zeros do not appear to be handled in my current code. I've seen this problem before and I think I was trying to be too precise and handle it exactly as it came up instead of making a more general solution. I will put up a test and a bug fix and try to get the new release out today. I'll tag you in the PR so you can test it if you'd like!
