### ISSUE TITLE
Support ExtAcks

### ISSUE THREAD

**Issue by isomer** [jbaublitz/neli#170]
**Would adding this feature cause a breaking change?**
Maybe - Depends on how it's implemented.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I get errors like "EINVAL" back from the kernel.  Figuring out exactly what is invalid is complicated and annoying.

**Describe the solution you'd like**
The kernel appears to support "extacks" which are extended error strings on netlink messages: https://lwn.net/Articles/719721/ / https://grep.app/search?q=NL_SET_ERR_MSG

This is enabled with a setsockopt:
```
  setsockopt(fd, SOL_NETLINK, NETLINK_EXT_ACK, true);
```

Then extra attributes are included on the netlink error messages:
```c
struct nlmsgerr {
        int             error;
        struct nlmsghdr msg;
        /*
         * followed by the message contents unless NETLINK_CAP_ACK was set
         * or the ACK indicates success (error == 0)
         * message length is aligned with NLMSG_ALIGN()
         */
        /*
         * followed by TLVs defined in enum nlmsgerr_attrs
         * if NETLINK_EXT_ACK was set
         */
};

/**
 * enum nlmsgerr_attrs - nlmsgerr attributes
 * @NLMSGERR_ATTR_UNUSED: unused
 * @NLMSGERR_ATTR_MSG: error message string (string)
 * @NLMSGERR_ATTR_OFFS: offset of the invalid attribute in the original
 *       message, counting from the beginning of the header (u32)
 * @NLMSGERR_ATTR_COOKIE: arbitrary subsystem specific cookie to
 *      be used - in the success case - to identify a created
 *      object or operation or similar (binary)
 * @NLMSGERR_ATTR_POLICY: policy for a rejected attribute
 * @__NLMSGERR_ATTR_MAX: number of attributes
 * @NLMSGERR_ATTR_MAX: highest attribute number
 */
```
  -- /usr/include/linux/netlink.h

Instead of NlPayload::Err() returning an std::io::Error, it could return a different Error type that includes all the extra metadata, and a nested std::io::Error.

This would drastically help with providing better error messages, and would avoid me pulling my hair out when I screw up and get yet another mysterious EINVAL.

**Describe alternatives you've considered**
The obvious alternative would not be to implement ExtAck support.

But more usefully, another option would be for NlPayload::Err to continue to implement a std::io::Error but the msg would be from NLERRMSG_ATTR_MSG instead of "Invalid Argument" (although I can't see a way in the standard library to do that).

Another variant would be to have std::io::Error wrap a different error that contains more information but continues to set ErrorKind correctly.

**Comment by jbaublitz** [comment]
Hi @isomer! I've seen this capability described in the kernel code before but hadn't dug into it too much. This seems like it could absolutely be valuable! What I'm mostly confused about is what you mean by `NlPayload::Err(_)` returning an IO error. That should only happen if there was an error in the socket operations themselves in which case you won't receive a netlink packet error in return. This is the kernel telling you that you made an incorrect syscall. However, if you send a well formed netlink packet and set everything up properly but there is an error in the netlink packet contents, then you will get a message in response outlining the error. It may be worth giving me an example of a case in which you've seen the IO error returned so that I confirm my guess.

Regardless, I think this is a valuable feature! Thanks for suggesting it!

**Comment by isomer** [comment]
You're right, I had forgotten I convert things to a std::os::Error very early on and thought that it was neli doing that.  My apologies.

I played with it a little bit this evening trying to make a simple example case to demonstrate what currently happens.  And it turns out that it muddles the attributes into the nlmsg!  So you get a combination of both your attributes, *and* the NLMSGERR_ATTR attributes in there.

I've written a stripped down program using nl80211 with the same caveats as last time.  It's possible that this could be done with Rt but I ran out of weekend before I could experiment with that (and thus some of this code is a little... rough).  This example relies on the fact that the kernel does some initial type checking of attributes before it does anything else with the message, so I pass a 1 byte mac address to GetInterface which is clearly wrong which is then flagged and returned with an only slightly error message.

I suspect that neli is just consuming attributes until the buffer is empty, where neli should only be consuming attributes for the length provided in the netlink header.

This requires neli and libc.

```rust
use libc::{setsockopt, NETLINK_EXT_ACK, SOL_NETLINK};
use neli::{
    consts::{
        nl::{GenlId, NlmF, NlmFFlags},
        socket::NlFamily,
    },
    err::NlError,
    genl::{Genlmsghdr, Nlattr},
    nl::{NlPayload, Nlmsghdr},
    socket::NlSocketHandle,
    types::GenlBuffer,
};
use std::os::unix::io::{FromRawFd as _, IntoRawFd as _};

#[neli::neli_enum(serialized_type = "u8")]
pub enum Nl80211Command {
    GetInterface = 5,
    /* Others elided */
}
impl neli::consts::genl::Cmd for Nl80211Command {}

#[neli::neli_enum(serialized_type = "u16")]
pub enum Nl80211Attribute {
    Mac = 6,
    /* Attributes Elided */
}
impl neli::consts::genl::NlAttrType for Nl80211Attribute {}

#[neli::neli_enum(serialized_type = "u16")]
pub enum ExtAckAttr {
    Unused = 0,
    Msg = 1,
    Offs = 2,
    Cookie = 3,
    Policy = 4,
}
impl neli::consts::genl::NlAttrType for ExtAckAttr {}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();
    let mut sock = NlSocketHandle::connect(
        NlFamily::Generic, /* family */
        Some(0),           /* pid */
        &[],               /* groups */
    )?;
    unsafe {
        let fd = sock.into_raw_fd();
        let enable = 1_i32;
        if setsockopt(
            fd,
            SOL_NETLINK,
            NETLINK_EXT_ACK,
            &enable as *const _ as *const _,
            std::mem::size_of::<i32>() as _,
        ) == -1
        {
            return Err(std::io::Error::last_os_error().into());
        }
        sock = NlSocketHandle::from_raw_fd(fd);
    }

    let family_id = sock.resolve_genl_family("nl80211")?;
    let mut attrs = GenlBuffer::new();

    attrs.push(
        Nlattr::new(
            /* Nested */ false,
            /* Network Byte Order */ false,
            /* Attribute */ Nl80211Attribute::Mac,
            /* Value */ vec![0_u8], /* NOTE: Deliberately wrong length */
        )
        .unwrap(),
    );

    let req = Nlmsghdr::new(
        /* len */ None,
        /* type */ family_id,
        /* flags */ NlmFFlags::new(&[NlmF::Request, NlmF::Ack]),
        /* seq */ Some(1),
        /* pid */ Some(0),
        /* payload */
        NlPayload::Payload(Genlmsghdr::<Nl80211Command, Nl80211Attribute>::new(
            /* cmd */ Nl80211Command::GetInterface,
            /* version */ 1,
            /* attrs */ attrs,
        )),
    );

    sock.send(req)?;
   loop {
        let data: Result<
            Option<Nlmsghdr<GenlId, Genlmsghdr<Nl80211Command, Nl80211Attribute>>>,
            _,
        > = sock.recv();
        match data {
            Ok(msgs) => {
                println!("msgs: {:?}", msgs);
            }
            Err(NlError::Nlmsgerr(e)) => {
                println!("msg err: {:?}", e);
                println!(
                    "unix error: {:?}",
                    std::io::Error::from_raw_os_error(-e.error)
                );
                for attr in e.nlmsg.nl_payload.get_attr_handle().iter() {
                    match ExtAckAttr::from(u16::from(&attr.nla_type)) {
                        ExtAckAttr::Msg => {
                            println!(
                                "Msg={:?}",
                                String::from_utf8(attr.nla_payload.as_ref().to_vec())
                            );
                        }
                        ExtAckAttr::Offs => {
                            println!("Offs={:?}", attr.nla_payload.as_ref());
                        }
                        ExtAckAttr::Cookie => {
                            println!("Cookie={:?}", attr.nla_payload.as_ref());
                        }
                        ExtAckAttr::Policy => {
                            println!("Policy={:?}", attr.nla_payload.as_ref());
                        }
                        _ => println!("attr: {:?}", attr),
                    }
                }
            }
            Err(e) => {
                println!("err: {:#?}", e);
            }
        }
    }
}
```

The output on my machine is:
```
msg err: Nlmsgerr { error: -34, nlmsg: NlmsghdrErr { nl_len: 28, nl_type: UnrecognizedConst(35), nl_flags: NlmFFlags(FlagBuffer(5, PhantomData)), nl_seq: 1, nl_pid: 0, nl_payload: Genlmsghdr { cmd: GetInterface, version: 1, reserved: 0, attrs: GenlBuffer([Nlattr { nla_len: 5, nla_type: AttrType { nla_nested: false, nla_network_order: false, nla_type: Mac }, nla_payload: Buffer([0]) }, Nlattr { nla_len: 39, nla_type: AttrType { nla_nested: false, nla_network_order: false, nla_type: UnrecognizedConst(1) }, nla_payload: Buffer([98, 105, 110, 97, 114, 121, 32, 97, 116, 116, 114, 105, 98, 117, 116, 101, 32, 115, 105, 122, 101, 32, 111, 117, 116, 32, 111, 102, 32, 114, 97, 110, 103, 101, 0]) }, Nlattr { nla_len: 8, nla_type: AttrType { nla_nested: false, nla_network_order: false, nla_type: UnrecognizedConst(2) }, nla_payload: Buffer([20, 0, 0, 0]) }, Nlattr { nla_len: 28, nla_type: AttrType { nla_nested: true, nla_network_order: false, nla_type: UnrecognizedConst(4) }, nla_payload: Buffer([8, 0, 6, 0, 6, 0, 0, 0, 8, 0, 7, 0, 6, 0, 0, 0, 8, 0, 1, 0, 10, 0, 0, 0]) }]) } } }
unix error: Os { code: 34, kind: Uncategorized, message: "Numerical result out of range" }
attr: Nlattr { nla_len: 5, nla_type: AttrType { nla_nested: false, nla_network_order: false, nla_type: Mac }, nla_payload: Buffer([0]) }
Msg=Ok("binary attribute size out of range\u{0}")
Offs=[20, 0, 0, 0]
attr: Nlattr { nla_len: 28, nla_type: AttrType { nla_nested: true, nla_network_order: false, nla_type: UnrecognizedConst(4) }, nla_payload: Buffer([8, 0, 6, 0, 6, 0, 0, 0, 8, 0, 7, 0, 6, 0, 0, 0, 8, 0, 1, 0, 10, 0, 0, 0]) }
```

Note the: "binary attribute size out of range\u{0}"

I also ran out of time as to why it's showing as UnrecognizedConst(4) for ExtAckAttr::Policy (and I have no idea how to interpret the contents of that anyway).

**Comment by isomer** [comment]
This looks fantastic!  Thank you very much, this will make debugging much much more pleasant and much easier to understand what's going wrong.

I've left a comment in the PR with I think a minor improvement - Should the u16 instead be a enum?  Especially given it's an enum in the C header.

If nothing else, it'll make Debug dumps a little bit clearer for people who are trying to debug wtf going on.
