### ISSUE TITLE
Build of examples is broken

### ISSUE THREAD

**Issue by fpagliughi** [jbaublitz/neli#174]
**Version of neli**
Tested:
`master` branch
`neli-v0.6.1` branch

**Describe the bug**

```
   Compiling neli v0.6.1 (/home/fmp/opensrc/rust/linux/neli)
error[E0432]: unresolved import `neli::socket::tokio`
  --> examples/async_nl80211.rs:15:13
   |
15 |     socket::tokio::NlSocket,
   |             ^^^^^ could not find `tokio` in `socket`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `neli` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**To Reproduce**

`$ cargo build --examples`

or 

`$ cargo test`

**Expected behavior**

Build & run unit tests without error. :-)

**Additional context**

Running on Linux Mint 19 (Ubuntu 18.04)

**Comment by jbaublitz** [comment]
Hi @fpagliughi, I've looked into this and I see a few options. For one, I provide a Cargo.toml file in the examples directory though that may be good to remove and opt for using the `cargo build --examples` command instead. It doesn't look like cargo supports compiling examples only if a feature is enabled so I'll likely have to conditionally compile `async_nl80211.rs` as

```
fn main {}
```

if the async feature is not enabled. Would that satisfy your needs?
