### ISSUE TITLE
Add from<libc::c_uint> for IffFlags

### ISSUE THREAD

**Issue by isomer** [jbaublitz/neli#178]
**Would adding this feature cause a breaking change?**
No.

**Is your feature request related to a problem? Please describe.**

`rtnetlink(7)` describes Ifinfomsg.ifi_change as:
```
ifi_change is reserved for future use and should be always set to 0xFFFFFFFF.
```

However this is ugly to do with the existing IffFlags type, the best solution I've found is:
```
IffFlags::new(&[Iff::UnrecognizedConst(0xFFFFFFFF)]),
```
This is setting a flag with multiple bits, which seems wrong.

**Describe the solution you'd like**

Implement `From<libc::c_uint> for IffFlags` (via implementing `From<ty>` in `impl_flags!`), so I instead can write:
```
 0xFFFFFFFF.into(),
```
when constructing `Ifinfomsg`.

Ideally, there would be a `From<IffFlags> for libc::c_uint` too (for symmetry) but this isn't necessary.

**Describe alternatives you've considered**

 * have `IffFlags::new()` take an `Option<>` for `ifi_changed`, and set it to 0xFFFFFFFF internally if not specified.  This is a breaking change, and not particularly general.  A variation on this, since ifi_changed is not yet used, to just drop the parameter from `IffFlags::new()` and hard code the value to 0xFFFFFFFF.
 *  have impl_flags! create a `full()` method, to create symmetry with the existing `empty()`.  This isn't as general as just allowing you to convert back and forth to the underlying type, and seems like pointless symmetry.

**Comment by jbaublitz** [comment]
Hi @isomer, this is likely a documentation bug. I've looked at the kernel code and it uses flags like `IFF_UP`/`IFF_DOWN` to control interface status so it does not need to always be set to `0xffffffff`. I even saw on Github that it seems to work around passing in 0 to change all flags to the flags passed in:

https://github.com/torvalds/linux/blob/master/net/core/rtnetlink.c#L863-L866

My thought here is that there may be something I can do with regards to adding a special case for "all flags set". Would that help?

**Comment by jbaublitz** [comment]
Hi @isomer! I think I'm going to move forward with the "all flags set" option if you don't have any additional feedback. I'm also going to be hopefully starting on #107 soon.

**Comment by isomer** [comment]
This seems reasonable, I think I'd still prefer a way to convert in/out to the underlying type, but this covers enough of my use case to solve my problem and I'm not that tied to needing a particular solution.

so all flags set, and bitsets seems reasonable to me.

**Comment by jbaublitz** [comment]
I decided to add your original functionality suggestion. I'm putting up a PR shortly.
