### ISSUE TITLE
tc -s qdisc show, but with rust-netlink

### ISSUE THREAD

**Issue by dtaht** [jbaublitz/neli#207]
**Would adding this feature cause a breaking change?**
No

**Is your feature request related to a problem? Please describe.**
In my work I sometimes (often) need to sample the qdisc statistics at a very, very high rate, on machines pushing tons of data. To date, in flent.org's implementation, I have a custom C parser for the tc command, and in libreqos.io, essentially a tc -s -j qdisc show | rust_parser_from_tc_json, which, in production on dumping 10k htb + cake queues at 10Gbit, is eating more cpu (at a 30ms samplerate) than I'd like.  

**Describe the solution you'd like**
Understanding what the process "should be" to move qdisc-related packet parsing from the linux kernel uapi + the userspace iproute2/tc code to this rust library. (there are an awful lot of in C tc qdisc netlink parsers for red, blue, pfifo, mq, etc, etc) Would it be best to attempt to import the C defines from the linux kernel uapi/whatever.h, transliterate the C code there to rust, try linking to the iproute library, or ... ?

Getting to a simple sample implementation of how to dump tc stats from one complicated qdisc type (mq+htb +cake is the worst one, but also one of the most common) would aid covering the rest of qdisc complexities. 

Being able to reconfigure qdiscs on the fly would be great too.

I'm not asking so much for someone to code this up, but how to think about, and then re-implement these complicated subsystems in a rust crate, sanely. As one example of a problem, over time, all these qdiscs add features and statistics via the tc xstats, so an older build of rust may see a bigger result than expected but shouldn't crash, and vice versa,  a binary of rust built on a newer system might see a smaller result than expected. 

https://github.com/LibreQoE/LibreQoS/issues/159

https://github.com/LibreQoE/LibreQoS/issues/156

**Comment by jbaublitz** [comment]
@dtaht I'll take a look at this and see what I can find in terms of whether the data structures you need for this are already implemented in neli. If they aren't, I'd be happy to collaborate with you on putting them in!

**Comment by dtaht** [comment]
@jbaublitz 

@thebracket  made *enormous* progress on this the other day. I frankly don't believe his early numbers, but a speedup of over a 100 and less than 4000 in hauling qdisc data out of the kernel seems feasible. We meet regularly in the #libreqos:matrix.org channel if you would like to drop in. 

https://github.com/LibreQoE/LibreQoS/blob/main/src/rust/netlink_testing/src/main.rs

**Comment by jbaublitz** [comment]
I looked at your code and you're actually using a different netlink library. Are you looking to migrate to neli?

**Comment by thebracket** [comment]
That's my fault - I committed an experiment, which was meant to be in a
local branch. I've been trying an assortment of netlink crates, mostly
looking to see what's around. Neli does seem to be the only one being
actively maintained/developed.

**Comment by jbaublitz** [comment]
I am just about to put out a v0.7.0-rc1 release. I'd recommend looking at that and see if it meets your performance needs. Happy to work on profiling/performance improvements if we need to.

**Comment by jbaublitz** [comment]
@thebracket Just FYI, I think something slipped through the cracks in the packaging process because crates.io points to the original developer's archived repositories for the main alternative to neli. See https://github.com/rust-netlink/ for the actively maintained alternatives.

**Comment by jbaublitz** [comment]
Any update on this or should I close this issue?

**Comment by thebracket** [comment]
I'd close it, we focused on other issues. Thanks!
