### ISSUE TITLE
Route multicast events (with `nl_pid > 0`) are ignored

### ISSUE THREAD

**Issue by acheronfail** [jbaublitz/neli#218]
I'm trying to make something that functions similar to [`nl-monitor ipv4-ifaddr`](https://github.com/thom311/libnl/blob/main/src/nl-monitor.c) with `neli`, but I'm struggling to get anywhere with it.

This is my current attempt:

```rust
let (socket, mut multicast) =
    NlRouter::connect(NlFamily::Route, None, Groups::empty()).unwrap();

socket
    .add_mcast_membership(Groups::new_groups(&[RTNLGRP_IPV4_IFADDR]))
    .unwrap();

match multicast.next() {
    None => unreachable!(),
    Some(response) => {
        dbg!(response).unwrap();
    }
}
```

As far as I can tell, this should be reporting events any time an ipv4 address on the machine changes, but I get no output at all with this setup. I've been looking at how `nl-monitor` works, and comparing that to `neli` and they look very similar here, so I'm not sure what's different...

Any chance you might know where I should look next? :pray:

**Comment by acheronfail** [comment]
Just used `strace` and I can see that messages are coming through, it's just that `multicast.next()` never returns. 

```txt
recvfrom(9, [
    {
        nlmsg_len=80,
        nlmsg_type=RTM_NEWADDR,
        nlmsg_flags=0,
        nlmsg_seq=1688203532,
        nlmsg_pid=8187
    },
    {
        ifa_family=AF_INET,
        ifa_prefixlen=32,
        ifa_flags=IFA_F_PERMANENT,
        ifa_scope=RT_SCOPE_UNIVERSE,
        ifa_index=if_nametoindex("wlan0")
    },
    [
        [
            {
                nla_len=8,
                nla_type=IFA_ADDRESS
            },
            inet_addr("10.0.0.254")
        ],
        [
            {
                nla_len=8,
                nla_type=IFA_LOCAL
            },
            inet_addr("10.0.0.254")
        ],
        [
            {
                nla_len=10,
                nla_type=IFA_LABEL
            },
            "wlan0"
        ],
        [
            {
                nla_len=8,
                nla_type=IFA_FLAGS
            },
            IFA_F_PERMANENT
        ],
        [
            {
                nla_len=20,
                nla_type=IFA_CACHEINFO
            },
            {
                ifa_prefered=4294967295,
                ifa_valid=4294967295,
                cstamp=38685,
                tstamp=38685
            }
        ]
    ]
], 32768, 0, NULL, NULL) = 80
```

Is this because I need a specific type before `neli` will parse it and return it? If so, is there a way to always return any message?

**Comment by acheronfail** [comment]
Alright, I just discovered that I can initialise a logger and use `RUST_LOG=trace` for more debug information about what `neli` is doing.

I've also built with `RUSTFLAGS=-g` so debug symbols are included and I can debug/step-through `neli` with a debugger.

My current findings are that the `senders` collection here is always empty, and the message's `pid` is non-zero, and so although `neli` receives and parses the message, it doesn't send it back to the `multicast` receiver in my example.

I have used a similar setup and gotten it working before with generic netlink apis, I'll update this with any further findings...

**Comment by acheronfail** [comment]
I can confirm that `nl-monitor ipv4-ifaddr` also receives events on its equivalent of a multicast received with `nl_pid != 0` and `nl_seq = <random high number>`.

So, I think this is a bug or oversight in `neli` then? Should events with `nl_pid > 0` and without a specific sender (matched by `nl_seq`) be ignored?

**Comment by acheronfail** [comment]
Alright, the whole thing is working (**provided my fork that's in https://github.com/jbaublitz/neli/pull/219 is used**).

Here's some sample code:

```rust
// setup socket for netlink route
let (socket, mut multicast) =
    NlRouter::connect(NlFamily::Route, None, Groups::empty()).unwrap();

// add multicast membership for ipv4-addr updates
socket
    .add_mcast_membership(Groups::new_groups(&[RTNLGRP_IPV4_IFADDR]))
    .unwrap();

// listen for multicast events
// NOTE: currently requires the changes here: https://github.com/jbaublitz/neli/pull/219
type Next = Option<Result<Nlmsghdr<u16, Ifaddrmsg>, RouterError<u16, Ifaddrmsg>>>;
match multicast.next_typed::<u16, Ifaddrmsg>() as Next {
    None => todo!(),
    // we got a multicast message
    Some(response) => {
        // if there are errors on the multicast channel, they'll be here in this result
        let response = response.unwrap();
        // get message payload
        let ifaddr_msg = response.get_payload().unwrap();
        // get a handle to the message's rt attributes
        let rt_attrs_handle = ifaddr_msg.rtattrs().get_attr_handle();
        // get the address attribute
        let addr_attr = rt_attrs_handle.get_attribute(Ifa::Address).unwrap();
        // convert the raw bytes from the attribute into an `Ipv4Addr` struct
        let bytes: &[u8] = addr_attr.rta_payload().as_ref();
        let bytes: &[u8; 4] = bytes.try_into().unwrap();
        let ipv4 = Ipv4Addr::from(*bytes);
        // 🎉 we did it!
        dbg!(ipv4);
    }
}
```

**Comment by acheronfail** [comment]
Wait - I'm so sorry for all the spam :sweat_smile: - after looking at this again I seem to have completely glossed over the fact that `nl-monitor` receives events with `nl_pid == 0` but when I try with `neli` I get events with `nl_pid > 0`!

So, the PR I created is probably bogus - these should be multicast events... but why don't the events come through with `nl_pid == 0` when I subscribe with `neli`??? This has got me so confused...

**Comment by jbaublitz** [comment]
@acheronfail Can you test #209 and let me know if that resolves the issue. Someone else suggested that I use `recvfrom` instead of `recv` to determine whether a message is coming from a netlink multicast group or not. Based on my initial testing, it seems to resolve the problem of heuristics. Can you please confirm that it resolves your issue too?

**Comment by acheronfail** [comment]
Ah yes! Thank you so much, I was going around in circle so many times :sweat_smile: 

I can confirm that works for me!
