### ISSUE TITLE
Build fails w/ stable rust

### ISSUE THREAD

**Issue by skrap** [jbaublitz/neli#22]
This crate depends on buffering, which includes a nightly-only feature flag:

```
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/buffering-0.3.3/src/lib.rs:2:1
  |
2 | #![feature(custom_attribute)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Is it possible to use this crate without nightly rust?

**Comment by skrap** [comment]
By the way, this is on rustc 1.35.0 (3c235d560 2019-05-20).

**Comment by jbaublitz** [comment]
@skrap Hey there, thanks for bringing this to my attention. This is actually an issue in the [buffering](https://github.com/jbaublitz/buffering) crate. I'm going to close this out and we can move the discussion over there.
