### ISSUE TITLE
rtnetlink: Support RTM_* constants in consts.rs

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#23]
@skrap I'm opening this to track support for rtnetlink `RTM_*` constants. Current plan is to implement an `Rtm` enum that implements `NlType` so it can be used in the `Nlmsghdr.nl_type` field as the documentation states it should be able to be used. I'm going to start with the libc PR and will point to [`jbaublitz/libc`](https://github.com/jbaublitz/libc) in Cargo.toml on master until it's merged then I'll do a new release.

**Comment by skrap** [comment]
@jbaublitz Awesome, I'll keep an eye out here.  🥇

**Comment by jbaublitz** [comment]
I saw your offer in the other issue to do an rtnetlink example using neli. This would be awesome! I haven't played much with that subsystem (but will eventually when I have time) so a PR of an example using that subsystem would be wonderful. Thanks again!

**Comment by jbaublitz** [comment]
Constants are available on master. The PR has not yet been merged so until then, master points to my libc where the only changes are the PR I submitted and master now has the `Rtm` enum available in `neli`. I'll close this out once I release `v0.4.3`.

**Comment by jbaublitz** [comment]
PR is merged. Updating `neli` to point at `rust-lang/libc` master branch and will release once that version's bumped.

**Comment by jbaublitz** [comment]
`0.4.3-r1` is up now. Closing.

**Comment by skrap** [comment]
Back from vacation now.  I'll check it out!
