### ISSUE TITLE
Extracting nested attributes

### ISSUE THREAD

**Issue by fpagliughi** [jbaublitz/neli#231]
**Is this a question about neli specifically? If so, please describe.**

I'm having the hardest time figuring how to parse out the nested attributes for the CAN parameters in a SocketCAN interface. The parameters are contained in the `LinkInfo` of a returned `Ifinfomsg`. The attribute has a `Buffer` that's roughly 140 bytes with the nested attributes. There are 17 possible attributes, all containing different types, like:

    BitTiming [1]  ->  pub struct can_bittiming { ... }
    BitTimingConst [2]  ->  pub struct can_bittiming_const { ... }
    Clock [3]  -> pb struct can_clock { ... }
    State [4]  -> u32

...etc. I've derived `FromBytes` for all the structs to deserialize them, but I can't figure out how to iterate through, or preferably, pull out individual attributes by index, like implementing: `get::<can_bittiming>(IflaCan::BitTiming)`

I find the `LinkInfo` like this:
```
if let Some(msg) = nl.recv::<'_, Rtm, Ifinfomsg>()? {
    if let Ok(payload) = msg.get_payload() {
	for attr in payload.rtattrs.iter() {
	    if attr.rta_type == Ifla::Linkinfo {
		println!("{:?}", attr);

                // ?!? Now what ?!?

	    }
	}
    }
    // ...
}
```

I've walked through the C code here:
https://github.com/lalten/libsocketcan/blob/b464485031b6f2a4e53d3ef1b3d405f9ba159c07/src/libsocketcan.c#L353-L539

but can't figure out how to implement the same in neli.

**Comment by fpagliughi** [comment]
Never mind. I eventually got it. 

The parameters were nested a couple layers deeper than I realized. And, at the inner layer, it would be helpful to add the missing CAN interface attribute types from [linux/can/netlink.h](https://github.com/torvalds/linux/blob/58720809f52779dc0f08e53e54b014209d13eebb/include/uapi/linux/can/netlink.h#L119-L145)

I'll follow up with a PR to add them shortly.

**Comment by jbaublitz** [comment]
Okay thank you!
