### ISSUE TITLE
Re-release with LICENSE file

### ISSUE THREAD

**Issue by ctron** [jbaublitz/neli#238]
It looks like the latest stable release (0.6.4) of the macros crate was released without a LICENSE file (it's present now).

As this is a problem for packaging for Fedora, I would like to ask if it's possible to re-release this one with a license file.

**Comment by jbaublitz** [comment]
@ctron Apologies for the delay. I'm actually a bit unclear on what would be best here largely because the most recent version of the neli-proc-macros crate does have the license file included in the tarball. Are you looking for a new release of neli on the 0.6.x release track? I see that the license file is not in the neli release, but I was under the impression that releasing a new version of the proc-macro crate was enough.

**Comment by ctron** [comment]
No worries. To my understanding the `0.7.x` release is still a pre-release, and it's not picked up by dependents. So, having a dependency tree, including `neli` would lead to a version which does not have a license file.

I guess re-releasing a `0.6.x` version would fix this, as such a version could be picked up by an existing dependency declaration of `0.6`.

**Comment by jbaublitz** [comment]
@ctron So if I'm understanding correctly, this is because of how Fedora determines package versions, and it's picking a package for neli-proc-macros that doesn't have a license file?

Basically I'm trying to figure out if I need to bump the required neli-proc-macros version on the 0.6.x track.

**Comment by ctron** [comment]
Yea, that's basically it. It's not only about determining the license, but actually including the license file, to my understanding at least.

**Comment by ctron** [comment]
The `rust2rpm` command triggers that issue. I just wanted to try it out, and it greeted me with a new option. It looks like it's no longer a requirement to have this as part of the crate, but I can provide it manually instead.

So maybe let's postpone any changes, and I'll try to get through with it that way.

**Comment by jbaublitz** [comment]
Okay, if you need me to put out a new release, just let me know, and I'm happy to put up a PR for your to test.

**Comment by jbaublitz** [comment]
Okay, I think this is resolved. Feel free to comment here and I'll reopen it if needed.
