### ISSUE TITLE
Support for routing table indices > 255

### ISSUE THREAD

**Issue by tbottomparallel** [jbaublitz/neli#243]
**Would adding this feature cause a breaking change?**
Yes - it would require modifying `neli::consts::rtnl::RtTable`

**Is your feature request related to a problem? Please describe.**
Yes - `rtnetlink` supports table id's up to `0xFFFFFFFF` but `RtTable::UnrecognizedConst(c_uchar)` only supports up to `u8::MAX`. (see <https://elixir.bootlin.com/linux/v6.10.8/source/include/uapi/linux/rtnetlink.h#L354>)

For example, table `51820` is typically used by wireguard.

**Describe the solution you'd like**
`RtTable::UnrecognizedConst(u32)` or a new enum variant allowing the full range of routing table id's.

**Describe alternatives you've considered**
None: cannot construct `neli::rtnl::Rtmsg` message for tables with id > 255.

**Additional context**
N/A

**Comment by jbaublitz** [comment]
Hi @tbottomparallel. I see the max that you linked, but I'm a bit confused as to how you want to support this given the definition of rtmsg in rtnetlink.h. As I see [here](https://elixir.bootlin.com/linux/v6.10.8/source/include/uapi/linux/rtnetlink.h#L243), it appears that this is represented as an unsigned char type. In Wireguard, how is this serialized in rtmsg when the maximum value allowed by rtmsg appears to be 255?

**Comment by tbottomparallel** [comment]
Oops, looks like I didn't do quite enough digging before opening the issue.

Looks like this is actually handled with an [attribute](https://www.man7.org/linux/man-pages/man7/rtnetlink.7.html):
`RTA_TABLE       int                   Routing table ID; if set, rtm_table is ignored`

and it looks like you already support this: https://docs.rs/neli/latest/neli/consts/rtnl/enum.Rta.html

Thanks for the quick investigation anyway.

**Comment by jbaublitz** [comment]
Sure thing! Always good for me to learn more about netlink. 🙂
