### ISSUE TITLE
Audit rtnetlink code before v0.5.0

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#29]
I need to review rtnetlink code quality and add some tests before releasing 0.4.3.

**Comment by skrap** [comment]
Related: I think the Ifinfomsg struct ser/deser is also incorrect — I will submit a fix once I have some more time to look at it.

**Comment by jbaublitz** [comment]
Some work has been done on this on branch `v0.4.3-r2`. I'm going to look into this at a higher level soon.

**Comment by jbaublitz** [comment]
I'm going to take a look at this. @skrap Any feelings on changing the `Rtattr` payload type to a generic with the trait bound of `Nl`? I don't think these attributes, contrary to generic netlink attributes, get nested which is the reason I chose more of a builder pattern in that case.

**Comment by jbaublitz** [comment]
I've taken a look and I'm realizing it may be best to leave the `Vec<u8>` typed payload as is. If different payloads in the same `Vec` have different types, the only way to represent that reasonably seems to be using binary payloads.

**Comment by skrap** [comment]
Sounds fine to me!

**Comment by jbaublitz** [comment]
I've just pushed a change to master that wraps `Vec<Rtattr<T, P>>` in a struct `Rtattrs<T, P>`. this will allow me to define helper methods on the attributes for parsing now that @skrap has added attributes everywhere they needed to be. I want parsing attributes to be simpler moving forward.

**Comment by jbaublitz** [comment]
To be nice to people using the library, I've changed this to target 0.5.0 so that people who need to update don't automatically pull in breaking changes. I'm going to cut a release without the breaking changes as 0.4.3.

**Comment by jbaublitz** [comment]
Closing.
