### ISSUE TITLE
open netlink socket with CLOEXEC

### ISSUE THREAD

**Issue by mbakhoff** [jbaublitz/neli#71]
The netlink socket is opened without the CLOEXEC flag. Rust standard library sets CLOEXEC for all the stuff it opens. Maybe it would make sense to do it in neli as well to avoid accidental leaks when creating child processes?

Should be easy to change in src/socket.rs NlSocket::new but it does have some backward compatibility concerns.. 

See also: https://github.com/rust-lang/rust/issues/12148

**Comment by jbaublitz** [comment]
This seems very reasonable for v0.5.0. Just a note that I'm catching up after a long vacation so it may take a bit.

**Comment by jbaublitz** [comment]
See the linked PR. Once CI passes, I'll merge and this can get closed out. Thanks for letting me know about this and for your patience!

**Comment by mbakhoff** [comment]
Awesome, thanks!
