### ISSUE TITLE
NlSocket::set_mcast_groups takes the group parameter as bit index

### ISSUE THREAD

**Issue by cxdong** [jbaublitz/neli#72]
By looking into the kernel implementation of netlink_setsockopt, when the optname is NETLINK_ADD_MEMBERSHIP, kernel takes the optval as the group id directly but not as a bit index.

The current implementation of NlSocket::set_mcast_groups seems takes the group parameter as some bit index vector, and then calculate to the group id number. This looks like not necessary and complicated.

If need to add group id=3, then in 'c' programming, we can call setsockopt(&id), and id just contains the value 3. In neli, need to call NlSocket::set_mcast_groups(vec![1, 2]), which seems not necessary and complicated.

So is it possible to do it by calling NlSocket::set_mcast_groups(3)? This seems more reasonable.

**Comment by jbaublitz** [comment]
This should be fixed in branch `v0.5.0-dev`. I reworked the API significantly. Closing.
