### ISSUE TITLE
Add convience methods and builder pattern for neli struct construction

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#83]
Currently, constructing larger and more complicated packets to be sent over netlink is not necessarily intuitive. Add some convenience functions for common use cases to avoid having to specify every field each time a header is created.

**Comment by jbaublitz** [comment]
@ollipa Do you mind if I add you to assignees here just to keep track of the fact that we're working on this together?

**Comment by ollipa** [comment]
Sure add me to the assignees :ok_hand:

**Comment by jbaublitz** [comment]
See PR #93 for a more in depth discussion.
