### ISSUE TITLE
Factor out nested attribute parsing into its own module

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#88]
Because both generic netlink and routing netlink can have nested attributes, factor this parsing code out into its own module that can be used in both cases.

@gluxon I was just going through my email, and I'm filing an issue for this so that I don't forget about it. Let me know if you have any feedback in the meantime!

**Comment by gluxon** [comment]
@jbaublitz No comments so far, but glad this is on the radar. Thanks!

**Comment by jbaublitz** [comment]
@gluxon This is now in the `v0.5.0-dev` branch. I'm going to try to put out a release today. I'm just doing documentation clean up.

**Comment by jbaublitz** [comment]
Merged. Closing.
