### ISSUE TITLE
Please remove `pub` from the `impl_*` macros and allow the caller to specify that

### ISSUE THREAD

**Issue by joshtriplett** [jbaublitz/neli#90]
In a library crate, I'd like to use the `impl_*` macros to define constants for a specific netlink protocol, but I don't want to expose any of those types as part of the library API. Those macros currently use `pub` explicitly. I've worked around this by putting them in a `mod private { ... }` block, but I'd rather not have to do that. Please consider changing the macros to define types/traits without any visibility, and let the user supply the desired visibility if any.

**Comment by jbaublitz** [comment]
Closed by 02a8f1ac46cb2fab5706e9137535d5d6019052d7
